### ISSUE TITLE
Improper undo after o or O with count

### ISSUE THREAD

**Issue by monkoose** [hrsh7th/cmp-buffer#32] opened 2021-12-09 09:24 UTC
minimal **init.lua**:

    require"cmp".setup({ sources = cmp.config.sources({ {name = 'buffer'} })})

steps to reproduce:
Open file that has some filetype, then `3o` or `11O` or something like this, type anything, quit insert mode and hit `u`. Only one line  removed and undo history shows that all is fine, so you can't undo this additional lines.

Haven't found such a problem with other sources.

**Comment by dmitmel** [comment] 2021-12-09 10:57
This may be a known issue in nvim-cmp. Can you try putting the following:

```lua
cmp.setup({
  -- ...
  experimental = {
    native_menu = true,
  },
  -- ...
})
```

into your config and seeing if the issue still reproduces?

**Comment by hrsh7th** [comment] 2021-12-09 11:04
neovim itself has a bug related this.
https://github.com/hrsh7th/nvim-cmp/issues/328
https://github.com/neovim/neovim/issues/11439

**Comment by monkoose** [comment] 2021-12-09 11:07
Yes, it fixes it, but at the same time popup now with default colors for kinds etc.

**Comment by dmitmel** [comment] 2021-12-09 14:30
Well, then this is a duplicate of https://github.com/hrsh7th/nvim-cmp/issues/328

**Closed** 2021-12-09 14:31 UTC
